name: gellary_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
   
  cupertino_icons: ^1.0.2  
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  conditional_builder_null_safety: ^0.0.6
  flutter_svg: ^0.22.0
  fluttertoast: ^8.1.1
  blurrycontainer: ^1.0.2
  flutter_screenutil: ^5.6.0
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.6
  splash_screen_view: ^3.0.0
  


  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/image_icon.png"
flutter:
  uses-material-design: true
  

  assets:
    - assets/images/
  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoe UI.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
